MODEL:
  ATT: True
  ATT_TYPE: 5
  PRETRAIN_CHOICE: 'imagenet'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'no'
  NAME: 'ViT-B-16'
  STRIDE_SIZE: [16, 16]
  ID_LOSS_WEIGHT : 0.25
  TRIPLET_LOSS_WEIGHT : 1.0
  I2T_LOSS_WEIGHT : 1.0
  # SIE_CAMERA: True
  # SIE_COE : 1.0

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  STAGE1:
    IMS_PER_BATCH: 32
    OPTIMIZER_NAME: "AdamW"
    BASE_LR: 5e-3
    WARMUP_LR_INIT: 2e-4
    LR_MIN: 2e-4
    WARMUP_METHOD: 'linear'
    WEIGHT_DECAY: 1e-4
    WEIGHT_DECAY_BIAS: 1e-4
    MAX_EPOCHS: 40
    CHECKPOINT_PERIOD: 20
    LOG_PERIOD: 50
    WARMUP_EPOCHS: 10
    FACTOR: 0.1
    FACTOR2: 0.0
    PR_MODEL: './logs_clip/duke_vit_0.5_pretrain/Duke_clipreid_ViT-B-16_60.pth'
    #    PR_MODEL: './logs_clip/duke_vit_0.2/ViT-B-16_60.pth'
#    PR_MODEL: 'no'
    OUTPUT_DIR: './logs/log_I2T/prompt_test'
  STAGE2:
    IMS_PER_BATCH: 48
    BASE_LR: 0.0002
    MAX_EPOCHS: 60
    CHECKPOINT_PERIOD: 10
    LOG_PERIOD: 100
    EVAL_PERIOD: 1
#    TARGET_MODEL: './logs/log_ITT_vit/5e-3_1.0_load_0.2/ViT-B-16_stage1_20.pth'
#    TARGET_MODEL: './logs_clip/duke_vit_0.2/ViT-B-16_60.pth'
    TARGET_MODEL: './logs_clip/duke_vit_0.5_pretrain/Duke_clipreid_ViT-B-16_60.pth'
    ADV_FACTOR: 10.0
    ADV_FACTOR_2: 0.0
    ADV_FACTOR_3: 10.0
    ADV_FACTOR_3_TYPE: 7
    ADV_FACTOR_3_MARGIN: 0.3
TEST:
  EVAL: True
  IMS_PER_BATCH: 64
  RE_RANKING: False
  WEIGHT: './model/Duke_baseline_ViT-B-16_60.pth'
#  WEIGHT: './logs/log_ITT_vit/5e-3_1.0_noload/ViT-B-16_stage1_20.pth'

  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

DATASETS:
   NAMES: ('dukemtmc')
   ROOT_DIR: ('../../dataSet')
OUTPUT_DIR: './logs/log_ITT_vit/5e-3_1.0_load_0.2'

#   NAMES: ('dukemtmc')
#   ROOT_DIR: ('')
# OUTPUT_DIR: ''

#   NAMES: ('occ_duke')
#   ROOT_DIR: ('')
# OUTPUT_DIR: ''

#   NAMES: ('msmt17')
#   ROOT_DIR: ('')
# OUTPUT_DIR: ''

# CUDA_VISIBLE_DEVICES=3 python train_clipreid.py --config_file configs/person/vit_clipreid.yml
